import type { Metadata } from 'next'
import { Geist, Geist_Mono, PT_Sans } from 'next/font/google'
import ReactQueryProvider from './utils/providers/ReactQueryProvider'
import { MuiThemeProvider } from './utils/providers/ThemeProvider'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const ptSans = PT_Sans({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-pt-sans',
})

export const metadata: Metadata = {
  title: 'Squanchy App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${ptSans.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <AppRouterCacheProvider>
          <MuiThemeProvider>
            <ReactQueryProvider>{children}</ReactQueryProvider>
          </MuiThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
